### PR TITLE
Readme fixes

### PR DESCRIPTION
**Pull request by LeoniePhiline**
For #11

### CODE REVIEW

**Comment by rodgomesc** [comment]
very good, thanks, could you add Avell G1513-FOX-7 in the list before I the merge ?, (this is my laptop)

**Comment by LeoniePhiline** [comment]
Ah, I see.
So this is a different barebone, right? Do you know which one it is? Is it from Tongfang or another manufacturer?
Since it's a different barebone from the ones I know, there are probably going to be still many more laptop models using this keyboard rgb controller...

Do you know which other models of https://avell.com.br/ might be compatible?

**Comment by LeoniePhiline** [comment]
The Tongfang barebone, but with different screen lid, would probably be:
- https://avell.com.br/g1750-rtx-muv
- https://avell.com.br/avell-g1750-muv
- https://avell.com.br/avell-c65-muv

**Comment by rodgomesc** [comment]
> Ah, I see.
> So this is a different barebone, right? Do you know which one it is? Is it from Tongfang or another manufacturer?
> Since it's a different barebone from the ones I know, there are probably going to be still many more laptop models using this keyboard rgb controller...
> 
> Do you know which other models of https://avell.com.br/ might be compatible?

I beleave, all avell laptops with mechanical keyboard shoud be compatible, but we not have way to test, so let's wait for user feedbacks

**Pull request merged**
