### PR TITLE
More styles, updated help

### PR DESCRIPTION
**Pull request by astiak**
Added more styles and updated help accordingly.
Updated Readme.md
Altered formatting of argparse description.

Please do note, I am not well versed in python! Review carefully, from all my testing everything appears to work as it should

### CODE REVIEW

**Comment by astiak** [comment]
I've added a bunch of styles. I really wanted to format the help command and add the option of brightness to the preset style, but my python skills are almost on existent!

I forgot to mention, I also added type int and choices to the brightness option so when incorrect options are passed, it exits more gracefully.

**Comment by rodgomesc** [comment]
Thanks, i'll Review this son as possible

**Comment by astiak** [comment]
Thanks rodgomesc.

I've just added one more style too (and the red, orange, yellow, green, blue, teal and purple options for it).

I wasn't quite sure what to name some of the styles, for example the `random` style. Feel free of course to rename to something more fitting.

In picking the other styles' names I just copied names of styles that exist on other keyboards (and appeared similar or the same) that I found on YouTube.

**Comment by rodgomesc** [comment]
thank you very much, i'm trying to set aside time to work on this project but recently i became daddy. but any day will still work

**Comment by astiak** [comment]
> thank you very much, i'm trying to set aside time to work on this project but recently i became daddy. but any day will still work

Congratulations on fatherhood, definitely life changing! Life is always more important.

Thank you for the amazing project in the first place, I'm very grateful that we can control the keyboard with ease.

**Comment by rodgomesc** [comment]
> > thank you very much, i'm trying to set aside time to work on this project but recently i became daddy. but any day will still work
> 
> Congratulations on fatherhood, definitely life changing! Life is always more important.
> 
> Thank you for the amazing project in the first place, I'm very grateful that we can control the keyboard with ease.

thankss, 

using this you can keep color scheme after system reboots, maybee it works in same way for mono color scheme

https://github.com/rodgomesc/avell-unofficial-control-center/blob/ffa1307f87c7774f253add2516ff41338117f137/aucc/main.py#L29

**Pull request merged**
