### PR TITLE
Fixed invalid error command when -d disable

### PR DESCRIPTION
**Pull request by joapuiib**
The program showed "Invalid or absent command" when run with -d option.

### CODE REVIEW

**Comment by rodgomesc** [comment]
sorry for the delayed feedback, i will check this next week

**Comment by rodgomesc** [comment]
someone tested ? I'm unable to test, my keyboard broke the flat cable

**Comment by astiak** [comment]
Tested all commits which impact function. No issues, works great!

Great to have style & brightness compatibility.

**Comment by rodgomesc** [comment]
> Tested all commits which impact function. No issues, works great!
> 
> Great to have style & brightness compatibility.

thank you

**Pull request merged**
