### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by brunotix**

### CODE REVIEW

**Comment by rodgomesc** [comment]
I appreciate your collaboration, but I do not think that using a shellscript to make adjustments is a good option, and soon after the implementation of the graphical interface that would be left unused, that is why I created the options to pass the parameters directly to the main.py, but there are other changes to make, you can start by updating README.md, explaining how to adjust the brightness options, whenever you want to commit, do not use Portuguese, so that the project maintains consistency in a single language so you can attract as many contributors as possible, not only from Brazil (more languages can be added when a graphical interface is created), thanks

**Comment by brunotix** [comment]
> I appreciate your collaboration, but I do not think that using a shellscript to make adjustments is a good option, and soon after the implementation of the graphical interface that would be left unused, that is why I created the options to pass the parameters directly to the main.py, but there are other changes to make, you can start by updating README.md, explaining how to adjust the brightness options, whenever you want to commit, do not use Portuguese, so that the project maintains consistency in a single language so you can attract as many contributors as possible, not only from Brazil (more languages can be added when a graphical interface is created), thanks


OK. I'll help as best I can. About the English language, the Avell are not very well known by these consumers. However I will contribute using English as far as I can. Thanks for listening.

**Comment by rodgomesc** [comment]
it is true that avell is not very well known outside of brazil, however this rgb keyboard comes from a company called tong fang, which distributes the same type of keyboard to companies that make customized notebooks around the world, so this algorithm will not only serve in the future for notebooks avell

**Comment by rodgomesc** [comment]
as you do not hear any more activities I will close this PR, any doubt look for me that I will open again

**Pull request closed without merging**
