### PR TITLE
Fix issue 9

### PR DESCRIPTION
**Pull request by astiak**
A fix for issue #9

### CODE REVIEW

**Comment by Quenix** [comment]
This fix worked for me. Thank you, man! My laptop is an Avell G1513 MxTI and I'm running Mint 19.

**Comment by astiak** [comment]
Thanks for verifying.

**Comment by astiak** [comment]
I realised that the brightness wasn't actually adjusting when used with -V or -H. Should be fixed now in the latest commit in this pull request.

**Comment by rodgomesc** [comment]
Thank you

**Comment by STOMPY05** [comment]
Hi, does anyone have the problem where the LEDS's blink for a second then turn themselves back off?

**Pull request merged**
